### ISSUE TITLE
Question - test_package

### ISSUE THREAD

**Issue by Eldadc** [memsharded/hello_vs#2]
Hi,

Question please. Some basic question.
How the consumer take the Hello lib , in his conan file there is no indication on Hellow Lib.

Thanks

**Comment by memsharded** [comment]
The documentation for this repo is here: https://docs.conan.io/en/latest/howtos/visual_studio_packages.html

Please follow steps and explanations in that docs page.

**Comment by Eldadc** [comment]
Thanks on the quick follow up.
After reading I am still do not understand how the consuming app "resolve" Hello lib with any
not in conanfile ?

Thanks

**Comment by memsharded** [comment]
I am sorry, but I cannot understand your question. Please try to put some code, the commands you are using, what is failing, what is the terminal output, etc, to try to understand what the issue could be. Thanks!

**Comment by Eldadc** [comment]
Hi,

Nothing fail, it is all working. I just want to understand if I run conan create . appcon/testing , the app is building correctly.
How the app grab the Hello Lib if nothing is mentioned in the conanfile under test_package

Thanks

**Comment by memsharded** [comment]
Hi @Eldadc 

Ok, got it. There are different things:

- The dependency to ``Hello/0.1@user/channel`` in ``test_package/conanfile.py`` is automatically injected. This is something automatic and specific of test_package. It works as it had defined in its recipe:

```python
    requires = "Hello/0.1@user/channel"
    generators = "cmake"

    def build(self):
        cmake = CMake(self)
        cmake.configure()
        cmake.build()
```

Then, the ``test_package/CMakeLists.txt`` contains the code:

```cmake
include(${CMAKE_BINARY_DIR}/conanbuildinfo.cmake)
conan_basic_setup()
```
To load the ``conanbuildinfo.cmake`` that was generated thanks to the ``generators="cmake"`` line in the recipe.

Does this solve your question? Thanks

**Comment by Eldadc** [comment]
Hi,

Almost.... On which conanfile there is entry  requires = "Hello/0.1@user/channel" , do not find it...

Thanks

**Comment by memsharded** [comment]
Is this one: https://github.com/memsharded/hello_vs/blob/master/test_package/conanfile.py

But it does NOT have it. It is automatically injected, on-the-fly, by conan, when ``conan create`` or ``conan test`` are called.

**Comment by Eldadc** [comment]
OK , So conan has some mechanism which to inject , It needs to be in same folder structure ?

**Comment by memsharded** [comment]
By default it needs to be inside a folder called ``test_package`` or ``test`` which lives besides the main package ``conanfile.py``. It can be put elsewhere, and with a different name, and then provide the ``--test-folder`` argument in the command line, or use the ``conan test`` command. The requirements is that it should be a ``conanfile.py`` too, and contain a ``test()`` method.

**Comment by Eldadc** [comment]
Ok , That is the missing link, the test command.
Thanks for your efforts to answer for me.

**Comment by memsharded** [comment]
No problem, glad it is solved :)
